spring:
#  config:
#    import: configserver:

  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
            - id: resource-service
              uri: lb://resource-service
              predicates:
                - Path=/api/resources/**
            - id: task-service
              uri: lb://task-service
              predicates:
                - Path=/api/tasks/**
            - id: incident-service
              uri: lb://incident-service
              predicates:
                - Path=/api/incidents/**
            - id: analytics-service
              uri: lb://analytics-service
              predicates:
                - Path=/api/analytics/**
    config:
      enabled: false

security:
  jwt:
    secret: DFHNYUTYFNYTBDVRSTS2323DDSFDFDFHHHFsdessedfgdhdhdDRGDHDH
    expiration: 3600000
    refresh:
      expiration: 604800000


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
#  metrics:
#    export:
#      prometheus:
#        enabled: true
